//
// Created by simon on 14.03.19.
//

#ifndef CGUE19_THECHOSENFROG_RUNTIMETYPEIDS_H
#define CGUE19_THECHOSENFROG_RUNTIMETYPEIDS_H

#endif //CGUE19_THECHOSENFROG_RUNTIMETYPEIDS_H

enum RuntimeTypeIds
{
    UPDATEABLE
};